// Build-time data access — everything here is a static import of JSON
// generated by `make webdata` (src/hotelareascore/webdata.py). No fetch, no
// runtime dependency: this is what keeps the page-view path free of any
// external call (CLAUDE.md §6).
import hotelsLondon from '../data/hotels-london.json';
import hotelsBangkok from '../data/hotels-bangkok.json';
import cityBaselines from '../data/city-baselines.json';
import personas from '../data/personas.json';
import meta from '../data/meta.json';
import type { CityBaseline, Hotel, Personas } from './types';

export const ALL_HOTELS: Hotel[] = [...(hotelsLondon as Hotel[]), ...(hotelsBangkok as Hotel[])];

export const HOTELS_BY_SLUG: Map<string, Hotel> = new Map(ALL_HOTELS.map((h) => [h.slug, h]));

export const CITY_BASELINES = cityBaselines as Record<string, CityBaseline>;

export const PERSONAS = personas as Personas;

export const BUILD_META = meta as { release: string; cities: string[] };

export function getHotel(slug: string): Hotel | undefined {
  return HOTELS_BY_SLUG.get(slug);
}

export function hotelsForCity(cityId: string): Hotel[] {
  return ALL_HOTELS.filter((h) => h.city_id === cityId);
}
