import { readFileSync } from 'node:fs';
import path from 'node:path';
// Build-only JSON parsing avoids TypeScript inferring millions of literal fields.
// Astro commands run from web/ (npm --prefix web); no client/runtime reads.
function readData(file: string): unknown {
  return JSON.parse(readFileSync(path.resolve(process.cwd(), 'src/data', file), 'utf8'));
}
// Build-time data access — everything here reads committed JSON during the build
// generated by `make webdata` (src/hotelareascore/webdata.py). No fetch, no
// runtime dependency: this is what keeps the page-view path free of any
// external call (CLAUDE.md §6).
const hotelsLondon = readData('hotels-london.json');
const hotelsBangkok = readData('hotels-bangkok.json');
const hotelsParis = readData('hotels-paris.json');
const hotelsRome = readData('hotels-rome.json');
const hotelsBarcelona = readData('hotels-barcelona.json');
const hotelsAmsterdam = readData('hotels-amsterdam.json');
const hotelsLisbon = readData('hotels-lisbon.json');
const hotelsSydney = readData('hotels-sydney.json');
const hotelsTokyo = readData('hotels-tokyo.json');
const hotelsDubai = readData('hotels-dubai.json');
const hotelsNewYork = readData('hotels-new_york.json');
const hotelsSingapore = readData('hotels-singapore.json');
const cityBaselines = readData('city-baselines.json');
const personas = readData('personas.json');
const meta = readData('meta.json');
const cityPages = readData('city-pages.json');
import type { CityBaseline, CityPage, Hotel, Personas } from './types';

// Each hotels-{city}.json is already the static-subset filtered export
// (src/hotelareascore/webdata.py's select_static_subset, docs/adr/013) --
// not "every hotel in the city," so this array is exactly the set of
// hotels with a real built page. Every other hotel in the full 12-city
// dataset is still in /data/search-index.json and gets the client-rendered
// limited-data card (web/src/pages/hotel/limited.astro) instead.
export const ALL_HOTELS: Hotel[] = [
  ...(hotelsLondon as Hotel[]),
  ...(hotelsBangkok as Hotel[]),
  ...(hotelsParis as Hotel[]),
  ...(hotelsRome as Hotel[]),
  ...(hotelsBarcelona as Hotel[]),
  ...(hotelsAmsterdam as Hotel[]),
  ...(hotelsLisbon as Hotel[]),
  ...(hotelsSydney as Hotel[]),
  ...(hotelsTokyo as Hotel[]),
  ...(hotelsDubai as Hotel[]),
  ...(hotelsNewYork as Hotel[]),
  ...(hotelsSingapore as Hotel[]),
];

export const HOTELS_BY_SLUG: Map<string, Hotel> = new Map(ALL_HOTELS.map((h) => [h.slug, h]));

export const CITY_BASELINES = cityBaselines as Record<string, CityBaseline>;

export const PERSONAS = personas as Personas;

export const BUILD_META = meta as { release: string; cities: string[] };

export const CITY_PAGES = cityPages as Record<string, CityPage>;

export function getHotel(slug: string): Hotel | undefined {
  return HOTELS_BY_SLUG.get(slug);
}

export function hotelsForCity(cityId: string): Hotel[] {
  return ALL_HOTELS.filter((h) => h.city_id === cityId);
}
