#!/usr/bin/env python3
"""Summarizes docs/reports/incident-2026-09-09-cloudflare-pages/probe.log
into up/down windows and durations (night mission #3, Tache 1) --
regenerate docs/reports/incident-2026-09-09-cloudflare-pages/probe-summary.md
hourly, alongside a fresh commit of probe.log, per the mission order.

"Healthy" status differs per URL (a 404 on a path that was never supposed
to exist, or on a sitemap while PUBLIC_INDEXING_ENABLED is off, is the
CORRECT answer, not a failure) -- see HEALTHY_STATUS below. status=0 means
the request itself failed (DNS/TLS/connect/timeout), always unhealthy.
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INCIDENT_DIR = ROOT / "docs" / "reports" / "incident-2026-09-09-cloudflare-pages"
LOG_PATH = INCIDENT_DIR / "probe.log"
SUMMARY_PATH = INCIDENT_DIR / "probe-summary.md"

HEALTHY_STATUS = {
    "https://staycontext.com/": {200},
    "https://staycontext.com/chemin-inexistant-probe": {404},
    "https://staycontext.com/sitemap-static.xml": {404},
    "https://staycontext.pages.dev/": {200},
}


def parse_ts(s: str) -> datetime:
    return datetime.strptime(s, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)


def main() -> int:
    if not LOG_PATH.exists():
        print(f"No log yet at {LOG_PATH}", file=sys.stderr)
        return 1

    by_url: dict[str, list[tuple[datetime, int, str]]] = defaultdict(list)
    with open(LOG_PATH, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            by_url[row["url"]].append((parse_ts(row["timestamp_utc"]), int(row["status"]), row["cf_ray"]))

    lines: list[str] = []
    lines.append("# Cloudflare Pages incident — probe summary")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/prod_probe_summary.py` from `probe.log` "
        "(30s cadence, `scripts/prod_probe.py`/`prod_probe_loop.sh`). This "
        "is the raw evidence for the Cloudflare support ticket."
    )
    lines.append("")

    total_rows = sum(len(v) for v in by_url.values())
    if total_rows == 0:
        lines.append("No probe data yet.")
        SUMMARY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Wrote {SUMMARY_PATH} (no data yet)")
        return 0

    first_ts = min(v[0][0] for v in by_url.values() if v)
    last_ts = max(v[-1][0] for v in by_url.values() if v)
    lines.append(f"**Window:** {first_ts.isoformat()} → {last_ts.isoformat()} "
                 f"({(last_ts - first_ts).total_seconds() / 3600:.2f}h, {total_rows} data points across 4 URLs)")
    lines.append("")

    # Found 2026-09-10: a status=0 (connection/DNS failure, not a real HTTP
    # response) hitting ALL 4 URLs -- including staycontext.pages.dev, a
    # completely different domain/zone from staycontext.com -- at the exact
    # same probe timestamp is the signature of a LOCAL network/DNS problem
    # on the machine running this probe, not a site-side incident (two
    # unrelated domains cannot genuinely go down in the same second for the
    # same local-resolver reason). Flagged explicitly so these windows are
    # never mistaken for real Cloudflare-side incidents (they'd otherwise
    # look identical to a down window in the per-URL sections below).
    by_ts: dict[datetime, dict[str, int]] = defaultdict(dict)
    for url, rows in by_url.items():
        for ts, status, _ in rows:
            by_ts[ts][url] = status
    local_blip_ts = [
        ts for ts, statuses in by_ts.items()
        if len(statuses) == len(HEALTHY_STATUS) and all(s == 0 for s in statuses.values())
    ]
    if local_blip_ts:
        local_blip_ts.sort()
        lines.append(
            f"**Likely local-probe network blip, not a site incident:** all 4 URLs "
            f"(including the unrelated `pages.dev` domain) returned a connection/DNS "
            f"failure (status=0) at the same instant, {len(local_blip_ts)} time(s) -- "
            f"{local_blip_ts[0].isoformat()} to {local_blip_ts[-1].isoformat()}. Two "
            f"independent domains cannot both genuinely go down together for a local-"
            f"resolver reason; this is almost certainly the probing machine's own "
            f"network (sleep/wake, Wi-Fi drop), not staycontext.com or Cloudflare. "
            f"Still counted as \"down\" in the per-URL sections below (the probe "
            f"genuinely couldn't verify anything during this window), but should NOT "
            f"be reported to Cloudflare support as a platform incident."
        )
        lines.append("")

    overall_longest_up = None
    for url, rows in by_url.items():
        healthy = HEALTHY_STATUS[url]
        lines.append(f"## `{url}`")
        lines.append("")

        status_counts: dict[int, int] = defaultdict(int)
        for _, status, _ in rows:
            status_counts[status] += 1
        counts_str = ", ".join(f"{s}: {c}" for s, c in sorted(status_counts.items()))
        n_healthy = sum(c for s, c in status_counts.items() if s in healthy)
        lines.append(f"- {len(rows)} probes, {n_healthy}/{len(rows)} healthy ({', '.join(str(h) for h in healthy)} expected). Status breakdown: {counts_str}")

        # Contiguous windows of healthy vs not, with duration.
        windows: list[tuple[str, datetime, datetime, int]] = []  # (kind, start, end, n)
        cur_kind = None
        cur_start = None
        cur_end = None
        cur_n = 0
        for ts, status, _ in rows:
            kind = "up" if status in healthy else "down"
            if kind != cur_kind:
                if cur_kind is not None:
                    windows.append((cur_kind, cur_start, cur_end, cur_n))
                cur_kind, cur_start, cur_n = kind, ts, 1
            else:
                cur_n += 1
            cur_end = ts
        if cur_kind is not None:
            windows.append((cur_kind, cur_start, cur_end, cur_n))

        down_windows = [w for w in windows if w[0] == "down"]
        up_windows = [w for w in windows if w[0] == "up"]
        total_down_s = sum((w[2] - w[1]).total_seconds() + 30 for w in down_windows)  # +30s: each row covers ~30s forward
        longest_up = max(((w[2] - w[1]).total_seconds() for w in up_windows), default=0)
        if overall_longest_up is None or longest_up < overall_longest_up:
            if url == "https://staycontext.com/":  # the mission's Tache 3 trigger is keyed to the home URL
                overall_longest_up = longest_up

        lines.append(f"- {len(down_windows)} down window(s), ~{total_down_s / 60:.1f} min total down time in this log")
        lines.append(f"- Longest continuous healthy streak: ~{longest_up / 60:.1f} min")
        if down_windows:
            lines.append("- Down windows:")
            for kind, start, end, n in down_windows:
                dur_s = (end - start).total_seconds() + 30
                lines.append(f"  - {start.isoformat()} → {end.isoformat()} (~{dur_s / 60:.1f} min, {n} probes)")
        lines.append("")

    lines.append("## Tache 3 trigger check")
    lines.append("")
    if overall_longest_up is not None and overall_longest_up >= 1800:
        lines.append(
            f"**TRIGGERED**: home URL longest continuous healthy streak is "
            f"~{overall_longest_up / 60:.1f} min (≥30 min threshold)."
        )
    else:
        streak = (overall_longest_up or 0) / 60
        lines.append(f"Not yet triggered — longest continuous healthy streak on the home URL so far: ~{streak:.1f} min (need ≥30 min).")

    SUMMARY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {SUMMARY_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
